# docker-compose.yml

services:

  django:
    build: ./backend/django_project
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    container_name: fraud_django
    ports:
      - "8000:8000"
    volumes:
      - ./backend/django_project:/app
    depends_on:
      - postgres
      - neo4j
      - nats
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NATS_URL=nats://nats:4222
      - DEBUG=True

  postgres:
    image: postgres:17-alpine
    container_name: fraud_postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j
    container_name: fraud_neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  nats:
    image: nats:2.10-alpine
    container_name: fraud_nats
    ports:
      - "4222:4222"                   # client connections
      - "8222:8222"                   # monitoring
    command: [ "-js", "-m", "8222" ]  # JetStream enabled

volumes:
  postgres_data:
  neo4j_data: